spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/.weasylearn/persistence/wasylearn
    username: wasylearner
    password: wasylearner
    driver-class-name: org.h2.Driver
