spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:2022/weasylearn"
    username: admin
    password: secret

  data:
    mongodb:
      host: localhost
      port: 2025
      database: weasylearn
      username: weasylearner
      password: weasylearner
      authentication-database: weasylearn

keycloak:
  auth-server-url: https://accounts.weasylearn.ro/auth
  realm: weasylearn-local
  resource: weasylearn-be
  bearer-only: true
  principal-attribute: preferred_username
  ssl-required: external
  use-resource-role-mappings: true
