version: '3.8'
services:
  mongodb_container:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 2025:27017
    volumes:
      - mongo-weasylearn-local:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  postgres:
    image: postgres:12.2
    restart: "no"
    environment:
      POSTGRES_DB: weasylearn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-weasylean-local:/var/lib/postgresql/data
    ports:
      - "2022:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "2021:80"
    volumes:
      - pgadmin-weasylean-local:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

volumes:
  mongo-weasylearn-local:
  postgres-weasylean-local:
  pgadmin-weasylean-local:
