name: Deploy

on:
  push:
    branches:
      - master
      - 'release/**'
      - develop

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build and Integration Test
        run: gradle clean build

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=weasylearn/weasylearn-backend
          VERSION=noop
          ENVIRONMENT=noop
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/})
            if [ "master" = "$VERSION" ]; then
              VERSION=stage
              ENVIRONMENT=stage
            elif [ "develop" = "$VERSION" ]; then
              VERSION=dev
              ENVIRONMENT=dev
            elif [[ $VERSION == release/* ]]; then
              VERSION=$(echo ${VERSION#release/})
              ENVIRONMENT=prod
            fi
          fi
          if [[ $VERSION == v-* ]]; then
            VERSION=$(echo ${VERSION#v-})
            TAGS="${DOCKER_IMAGE}:v-${VERSION},${DOCKER_IMAGE}:${VERSION}"
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:v-${MINOR},${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:v-${MAJOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=environment::${ENVIRONMENT}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: checkout envs repo
        uses: actions/checkout@master
        with:
          repository: cadeca/weasylearn-envs
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: weasylearn-envs

      - name: copy profile from envs repo
        run: |
          cp weasylearn-envs/${{ steps.prep.outputs.environment }}/backend/application-${{ steps.prep.outputs.environment }}.yml src/main/resources/application-${{ steps.prep.outputs.environment }}.yml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: registry.weasylearn.ro
          username: ${{ secrets.WL_REGISTRY_USERNAME }}
          password: ${{ secrets.WL_REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.prep.outputs.tags }}
